//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/MyAssets/ResourcePacks/Plugins/MyInputManager/Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""5ed32db6-a9e6-4df8-b22f-7e3726b11a35"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""da320e20-8a13-49c8-8be8-8a73885cdb8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move2"",
                    ""type"": ""Value"",
                    ""id"": ""1acd3a8a-5550-4c2f-bdae-e3a304c43b65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveBoost"",
                    ""type"": ""Value"",
                    ""id"": ""89836cf1-7457-42ca-b127-87eb4e58237c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveBoost2"",
                    ""type"": ""Value"",
                    ""id"": ""0e130ae2-9342-4a85-ae81-0607176aa569"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Value"",
                    ""id"": ""06d4df04-6d43-4864-9ceb-720fca81542d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack2"",
                    ""type"": ""Value"",
                    ""id"": ""055c6ea7-42f4-490a-a52e-a6db08f42523"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Value"",
                    ""id"": ""a34b85be-68d2-493a-be79-d5c39f9571ee"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PickUPItem"",
                    ""type"": ""Value"",
                    ""id"": ""e09b2cd9-df65-41a3-bb22-2afa7b636989"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FinalSkill"",
                    ""type"": ""Value"",
                    ""id"": ""086f6bd5-d376-47fd-a084-e3cc2599d0ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ExchangeWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""c270d12f-8211-47ce-a59b-bd7dbb624b3f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""8d9bf4df-0997-429b-ab8f-693390afada4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump2"",
                    ""type"": ""Value"",
                    ""id"": ""33656c9e-99b3-4c4d-96a6-97156eec1698"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""4afac2a6-a811-478b-b247-59dd93778080"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eba0ff1a-556c-4a58-9acb-400cdadc8531"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b8f298ef-74b5-4d06-a3ab-f6090cf71e87"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5c6c24fc-8f51-47eb-9e1a-124ff56ccf39"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c3546e1f-189e-420f-bcf2-d82e47a2b4eb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9bf774a5-a03a-4a21-8502-f2e03c18fa33"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e1e5676-e418-4629-b8ab-6e6b832bddeb"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a6f1ec9-da64-4302-a17a-f1d6c4d10da1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUPItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb765f67-95f9-4234-bd20-66a1e7f9d9ce"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c444bfe-e675-4ef4-8f2d-9953c5da8a78"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FinalSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dc712e5-3398-4430-8857-45957c4ab756"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExchangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""↑↓←→"",
                    ""id"": ""efdfd0f7-999c-44a3-9872-76489380a81f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d44f272b-4fe8-4293-b223-28cd0dedd0d6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d042802d-d917-4492-b7db-1f7295d1fc61"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f31daf0f-3cc1-4719-8f2c-5caa3b5c7d34"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d29bd986-0163-4046-a266-ca7db6dacfae"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ffb2c98c-b7fd-48b7-8410-8317127368b3"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBoost2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e60f3eb-cd3f-46de-89db-e4495d6ed708"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d566e0c7-eca7-4236-bb5a-6c4042711998"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f538bd12-9507-4ede-b33a-39c0cbc69cf1"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIPlay"",
            ""id"": ""82194e88-544a-410f-a4b3-30e58fc57918"",
            ""actions"": [
                {
                    ""name"": ""Return"",
                    ""type"": ""Value"",
                    ""id"": ""95cfe040-82cd-4b02-ae07-48cd25ed117f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a5de733f-0297-40b8-8de5-067253457d31"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""UIPlay"",
            ""bindingGroup"": ""UIPlay"",
            ""devices"": []
        }
    ]
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_Move = m_GamePlay.FindAction("Move", throwIfNotFound: true);
        m_GamePlay_Move2 = m_GamePlay.FindAction("Move2", throwIfNotFound: true);
        m_GamePlay_MoveBoost = m_GamePlay.FindAction("MoveBoost", throwIfNotFound: true);
        m_GamePlay_MoveBoost2 = m_GamePlay.FindAction("MoveBoost2", throwIfNotFound: true);
        m_GamePlay_Attack = m_GamePlay.FindAction("Attack", throwIfNotFound: true);
        m_GamePlay_Attack2 = m_GamePlay.FindAction("Attack2", throwIfNotFound: true);
        m_GamePlay_UseItem = m_GamePlay.FindAction("UseItem", throwIfNotFound: true);
        m_GamePlay_PickUPItem = m_GamePlay.FindAction("PickUPItem", throwIfNotFound: true);
        m_GamePlay_FinalSkill = m_GamePlay.FindAction("FinalSkill", throwIfNotFound: true);
        m_GamePlay_ExchangeWeapon = m_GamePlay.FindAction("ExchangeWeapon", throwIfNotFound: true);
        m_GamePlay_Jump = m_GamePlay.FindAction("Jump", throwIfNotFound: true);
        m_GamePlay_Jump2 = m_GamePlay.FindAction("Jump2", throwIfNotFound: true);
        // UIPlay
        m_UIPlay = asset.FindActionMap("UIPlay", throwIfNotFound: true);
        m_UIPlay_Return = m_UIPlay.FindAction("Return", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
    private readonly InputAction m_GamePlay_Move;
    private readonly InputAction m_GamePlay_Move2;
    private readonly InputAction m_GamePlay_MoveBoost;
    private readonly InputAction m_GamePlay_MoveBoost2;
    private readonly InputAction m_GamePlay_Attack;
    private readonly InputAction m_GamePlay_Attack2;
    private readonly InputAction m_GamePlay_UseItem;
    private readonly InputAction m_GamePlay_PickUPItem;
    private readonly InputAction m_GamePlay_FinalSkill;
    private readonly InputAction m_GamePlay_ExchangeWeapon;
    private readonly InputAction m_GamePlay_Jump;
    private readonly InputAction m_GamePlay_Jump2;
    public struct GamePlayActions
    {
        private @InputActions m_Wrapper;
        public GamePlayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_GamePlay_Move;
        public InputAction @Move2 => m_Wrapper.m_GamePlay_Move2;
        public InputAction @MoveBoost => m_Wrapper.m_GamePlay_MoveBoost;
        public InputAction @MoveBoost2 => m_Wrapper.m_GamePlay_MoveBoost2;
        public InputAction @Attack => m_Wrapper.m_GamePlay_Attack;
        public InputAction @Attack2 => m_Wrapper.m_GamePlay_Attack2;
        public InputAction @UseItem => m_Wrapper.m_GamePlay_UseItem;
        public InputAction @PickUPItem => m_Wrapper.m_GamePlay_PickUPItem;
        public InputAction @FinalSkill => m_Wrapper.m_GamePlay_FinalSkill;
        public InputAction @ExchangeWeapon => m_Wrapper.m_GamePlay_ExchangeWeapon;
        public InputAction @Jump => m_Wrapper.m_GamePlay_Jump;
        public InputAction @Jump2 => m_Wrapper.m_GamePlay_Jump2;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void AddCallbacks(IGamePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Move2.started += instance.OnMove2;
            @Move2.performed += instance.OnMove2;
            @Move2.canceled += instance.OnMove2;
            @MoveBoost.started += instance.OnMoveBoost;
            @MoveBoost.performed += instance.OnMoveBoost;
            @MoveBoost.canceled += instance.OnMoveBoost;
            @MoveBoost2.started += instance.OnMoveBoost2;
            @MoveBoost2.performed += instance.OnMoveBoost2;
            @MoveBoost2.canceled += instance.OnMoveBoost2;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Attack2.started += instance.OnAttack2;
            @Attack2.performed += instance.OnAttack2;
            @Attack2.canceled += instance.OnAttack2;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @PickUPItem.started += instance.OnPickUPItem;
            @PickUPItem.performed += instance.OnPickUPItem;
            @PickUPItem.canceled += instance.OnPickUPItem;
            @FinalSkill.started += instance.OnFinalSkill;
            @FinalSkill.performed += instance.OnFinalSkill;
            @FinalSkill.canceled += instance.OnFinalSkill;
            @ExchangeWeapon.started += instance.OnExchangeWeapon;
            @ExchangeWeapon.performed += instance.OnExchangeWeapon;
            @ExchangeWeapon.canceled += instance.OnExchangeWeapon;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Jump2.started += instance.OnJump2;
            @Jump2.performed += instance.OnJump2;
            @Jump2.canceled += instance.OnJump2;
        }

        private void UnregisterCallbacks(IGamePlayActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Move2.started -= instance.OnMove2;
            @Move2.performed -= instance.OnMove2;
            @Move2.canceled -= instance.OnMove2;
            @MoveBoost.started -= instance.OnMoveBoost;
            @MoveBoost.performed -= instance.OnMoveBoost;
            @MoveBoost.canceled -= instance.OnMoveBoost;
            @MoveBoost2.started -= instance.OnMoveBoost2;
            @MoveBoost2.performed -= instance.OnMoveBoost2;
            @MoveBoost2.canceled -= instance.OnMoveBoost2;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Attack2.started -= instance.OnAttack2;
            @Attack2.performed -= instance.OnAttack2;
            @Attack2.canceled -= instance.OnAttack2;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @PickUPItem.started -= instance.OnPickUPItem;
            @PickUPItem.performed -= instance.OnPickUPItem;
            @PickUPItem.canceled -= instance.OnPickUPItem;
            @FinalSkill.started -= instance.OnFinalSkill;
            @FinalSkill.performed -= instance.OnFinalSkill;
            @FinalSkill.canceled -= instance.OnFinalSkill;
            @ExchangeWeapon.started -= instance.OnExchangeWeapon;
            @ExchangeWeapon.performed -= instance.OnExchangeWeapon;
            @ExchangeWeapon.canceled -= instance.OnExchangeWeapon;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Jump2.started -= instance.OnJump2;
            @Jump2.performed -= instance.OnJump2;
            @Jump2.canceled -= instance.OnJump2;
        }

        public void RemoveCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);

    // UIPlay
    private readonly InputActionMap m_UIPlay;
    private List<IUIPlayActions> m_UIPlayActionsCallbackInterfaces = new List<IUIPlayActions>();
    private readonly InputAction m_UIPlay_Return;
    public struct UIPlayActions
    {
        private @InputActions m_Wrapper;
        public UIPlayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Return => m_Wrapper.m_UIPlay_Return;
        public InputActionMap Get() { return m_Wrapper.m_UIPlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIPlayActions set) { return set.Get(); }
        public void AddCallbacks(IUIPlayActions instance)
        {
            if (instance == null || m_Wrapper.m_UIPlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIPlayActionsCallbackInterfaces.Add(instance);
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
        }

        private void UnregisterCallbacks(IUIPlayActions instance)
        {
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
        }

        public void RemoveCallbacks(IUIPlayActions instance)
        {
            if (m_Wrapper.m_UIPlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIPlayActions instance)
        {
            foreach (var item in m_Wrapper.m_UIPlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIPlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIPlayActions @UIPlay => new UIPlayActions(this);
    private int m_UIPlaySchemeIndex = -1;
    public InputControlScheme UIPlayScheme
    {
        get
        {
            if (m_UIPlaySchemeIndex == -1) m_UIPlaySchemeIndex = asset.FindControlSchemeIndex("UIPlay");
            return asset.controlSchemes[m_UIPlaySchemeIndex];
        }
    }
    public interface IGamePlayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMove2(InputAction.CallbackContext context);
        void OnMoveBoost(InputAction.CallbackContext context);
        void OnMoveBoost2(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnAttack2(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnPickUPItem(InputAction.CallbackContext context);
        void OnFinalSkill(InputAction.CallbackContext context);
        void OnExchangeWeapon(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJump2(InputAction.CallbackContext context);
    }
    public interface IUIPlayActions
    {
        void OnReturn(InputAction.CallbackContext context);
    }
}
